services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cardboard_user
      - POSTGRES_PASSWORD=cardboard_password
      - POSTGRES_DB=cardboard
  redis:
    image: redis:alpine
  web:
    build:
      context: .
      dockerfile: Dockerfile.render
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://cardboard_user:cardboard_password@db/cardboard
      - REDIS_URL=redis://redis:6379
      - DJANGO_SUPERUSER_PASSWORD=burrito
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - DATABASE_URL=postgres://cardboard_user:cardboard_password@db/cardboard
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
